### ISSUE TITLE
Interrupt period

### ISSUE THREAD

**Issue by sidprice** [gregtomasch/USFSMAX#3]
We are using the USFSMAX in a new product design and I am trying to discover what sets the interrupt rate output from the module?

**Comment by gregtomasch** [comment]
Hi Sid,

The DRDY interrupt frequency is set by the accel/gyro data rate (should be the same) set for the LSM6DSM in "config.h"; the default is set at 834Hz

Best,
Greg

**Comment by sidprice** [comment]
Greg, Thanks for the quick reply. As an experiment I had changed both of those to 52Hz, the interrupt rate stayed around 800Hz. I checked the Config structure is getting the correct values. Any suggestions of what else I may be missing?
Sid

**Comment by gregtomasch** [comment]
Hi Sid,

This feels like a bug perhaps... I'm reviewing the FW code and it looks OK. Have you tried another value of the accel/gyro ODR's? Does it respond to another ODR value or is it always stuck on 834Hz?

As a related point, why do you need to slow down this interrupt? If you slow down the accel/gyro to 52Hz, the quality of the AHRS estimate will almost certainly suffer. Are you wanting to read/store the sensor data or are you just interested in the AHRS solution?

Best,
Greg

**Comment by sidprice** [comment]
Hi Greg, yes I have tried other values and it is stuck on 834Hz. In fact we are probably going to run at 1660Hz, when it did not change to that I tried a wildly different value, 52Hz.
Regards,
Sid

**Comment by gregtomasch** [comment]
Hi Sid,

I see... I will start experimenting to reproduce/troubleshoot. This will probably take a few days...

Best,
Greg

**Comment by sidprice** [comment]
HI Greg, no worries, we are in very early days with much work to be done.

BTW: I also noted with the Teensy 3.6 Arduino sketch, the I2C is running at 100KHz, even though 1MHz is selected. Just FYI.

Best regards,
Sid

**Comment by gregtomasch** [comment]
Hi Sid,

One last point... in one of your earlier posts you said," I checked the Config structure is getting the correct values." Does this mean you are calling "USFSMAX::Retreive_cfg()" from the host MCU to see the configuration the coprocessor is actually running? If so, does it accept the changes to the accel/gyro ODR's?

Thanks,
Greg

**Comment by sidprice** [comment]
Hi Greg,
No, I was looking at the values being sent to the module. So, I don't know if they are being accepted. If I get some time later I will retrieve the config data and check it.
Good suggestions.
Regards,
Sid

**Comment by gregtomasch** [comment]
Hi Sid,

Did a little more coding to read-back the config from the USFSMAX after startup; it is responding to config changes in the host MCU config. So at least using the Dragonfly STM32L4 dev board, the config is being received/loaded properly. Were you looking at the DRDY interrupt on an O-scope/logic analyzer? I will check with the O-scope to verify the interrupt frequency is actually changing.

BTW, when did you order/receive your USFSMAX board?

Best,
Greg

**Comment by sidprice** [comment]
Hi Greg,
I was measuring with logic analyzer.

The module was bought by my client at least a couple of months ago.
Regards,
Sid

**Comment by gregtomasch** [comment]
Hi Sid,

It sounds like you have an early unit... Although not specifically your issue, there were some other bugs in the FW that were fixed around that time that could be relevant. I will verify frequency change on the DRDY pin with config modification using the O-scope. Is/are your unit(s) on machine pin headers? I can exchange a re-flashed/calibrated unit on pin headers for your "Problem child" so you can verify that this is not an on-going issue...

Best,
Greg

**Comment by sidprice** [comment]
Hi Greg,
I soldered pin-headers to it for use in breadboard.
Regards,
Sid

**Comment by gregtomasch** [comment]
Hi Sid,

Verified... Setting accel/gyro ODR to  0x08 in the host MCU sketch gives me a 1.6kHz DRDY pulse frequency on the "int" pin. Contact me at "gregtomasch@gmail.com" if you want to arrange an exchange...

**Comment by gregtomasch** [comment]
Unit with updated FW has been shipped. We can re-open if you continue to experience issues...
