### ISSUE TITLE
Embedded Linux host

### ISSUE THREAD

**Issue by d1ken** [gregtomasch/USFSMAX#4]
Hello.
Can you help to find solution of connection MAX32660 Motion Co-Processor to embedded Linux host?
Something like Raspberry Pi.
Generally I want connect it to the MT7688 based board with OpenWRT (it has I2C and run Linux, but no FPU).
I need heading, roll and pith to fuse GNSS (installed on rover's roof) and calculate position on the ground.
Also I want try to implement inertial navigation system for situations of GNSS signal lost or RTK corrections signal lost.

**Comment by gregtomasch** [comment]
Sounds like an interesting project but I have no plans to do an Linux host development at this time...
